server.port=${PORT:8080}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.main.lazy-initialization=true

logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO

app.frontend.base-url=http://localhost:5173
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=${COOKIE_SECURE:false}